on:
  - push
  # - pull_request
  - workflow_dispatch
name: On self-hosted Runners
jobs:
  main:
    name: On self-hosted Runners
    runs-on: ubuntu-24.04
    # runs-on: self-hosted
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - name: 'TODO: ジョブを書く'
        run: |
          echo 'グローバルにマシン環境を汚すものは self-hosted に適していない'
          echo '時間がかかる API連携 や バッチ処理 などを実行するために使うことになるだろう'
