on:
  - push
  # - pull_request
  - workflow_dispatch
name: On self-hosted Runners
jobs:
  main:
    name: On self-hosted Runners
    runs-on: ubuntu-24.04
    # runs-on: self-hosted
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: 'TODO: ジョブを書く'
        run: |
          echo 'グローバルにマシン環境を汚すものは self-hosted に適していない'
          echo '時間がかかる API連携 や バッチ処理 などを実行するために使うことになるだろう'
